// Dữ liệu cứng 34 tỉnh thành Việt Nam
export const citiesData = [
  { CityID: 1, CityCode: "HCM", CityName: "Thành phố Hồ Chí Minh", Country: "Việt Nam", Description: "Thành phố lớn nhất Việt Nam, trung tâm kinh tế phía Nam" },
  { CityID: 2, CityCode: "HN", CityName: "Hà Nội", Country: "Việt Nam", Description: "Thủ đô của Việt Nam, trung tâm chính trị, văn hóa" },
  { CityID: 3, CityCode: "DN", CityName: "Đà Nẵng", Country: "Việt Nam", Description: "Thành phố biển xinh đẹp, trung tâm du lịch miền Trung" },
  { CityID: 4, CityCode: "HP", CityName: "Hải Phòng", Country: "Việt Nam", Description: "Thành phố cảng lớn nhất miền Bắc" },
  { CityID: 5, CityCode: "CT", CityName: "Cần Thơ", Country: "Việt Nam", Description: "Thủ phủ vùng Đồng bằng sông Cửu Long" },
  { CityCode: "AN", CityName: "An Giang", Country: "Việt Nam", Description: "Tỉnh biên giới Tây Nam, nổi tiếng với núi Sam, chùa Bà Chúa Xứ" },
  { CityCode: "BR", CityName: "Bà Rịa - Vũng Tàu", Country: "Việt Nam", Description: "Tỉnh ven biển phía Nam, nhiều bãi biển đẹp" },
  { CityCode: "BL", CityName: "Bạc Liêu", Country: "Việt Nam", Description: "Tỉnh Đồng bằng sông Cửu Long" },
  { CityCode: "BK", CityName: "Bắc Kạn", Country: "Việt Nam", Description: "Tỉnh miền núi phía Bắc" },
  { CityCode: "BG", CityName: "Bắc Giang", Country: "Việt Nam", Description: "Tỉnh trung du miền núi phía Bắc" },
  { CityCode: "BN", CityName: "Bắc Ninh", Country: "Việt Nam", Description: "Tỉnh đồng bằng Bắc Bộ, nổi tiếng với quan họ" },
  { CityCode: "BT", CityName: "Bến Tre", Country: "Việt Nam", Description: "Tỉnh Đồng bằng sông Cửu Long, xứ dừa" },
  { CityCode: "BD", CityName: "Bình Định", Country: "Việt Nam", Description: "Tỉnh duyên hải Nam Trung Bộ" },
  { CityCode: "BP", CityName: "Bình Phước", Country: "Việt Nam", Description: "Tỉnh miền Đông Nam Bộ" },
  { CityCode: "BU", CityName: "Bình Thuận", Country: "Việt Nam", Description: "Tỉnh duyên hải Nam Trung Bộ, nổi tiếng với Mũi Né" },
  { CityCode: "CM", CityName: "Cà Mau", Country: "Việt Nam", Description: "Tỉnh cực Nam của Tổ quốc" },
  { CityCode: "CB", CityName: "Cao Bằng", Country: "Việt Nam", Description: "Tỉnh miền núi phía Bắc, có thác Bản Giốc" },
  { CityCode: "DL", CityName: "Đắk Lắk", Country: "Việt Nam", Description: "Tỉnh Tây Nguyên, nổi tiếng với cà phê" },
  { CityCode: "DG", CityName: "Đắk Nông", Country: "Việt Nam", Description: "Tỉnh Tây Nguyên" },
  { CityCode: "DB", CityName: "Điện Biên", Country: "Việt Nam", Description: "Tỉnh miền núi Tây Bắc, nổi tiếng với chiến thắng Điện Biên Phủ" },
  { CityCode: "DD", CityName: "Đồng Nai", Country: "Việt Nam", Description: "Tỉnh miền Đông Nam Bộ" },
  { CityCode: "DT", CityName: "Đồng Tháp", Country: "Việt Nam", Description: "Tỉnh Đồng bằng sông Cửu Long" },
  { CityCode: "GL", CityName: "Gia Lai", Country: "Việt Nam", Description: "Tỉnh Tây Nguyên" },
  { CityCode: "HG", CityName: "Hà Giang", Country: "Việt Nam", Description: "Tỉnh cực Bắc, nổi tiếng với cao nguyên đá Đồng Văn" },
  { CityCode: "HD", CityName: "Hà Nam", Country: "Việt Nam", Description: "Tỉnh đồng bằng Bắc Bộ" },
  { CityCode: "HT", CityName: "Hà Tĩnh", Country: "Việt Nam", Description: "Tỉnh Bắc Trung Bộ" },
  { CityCode: "HDG", CityName: "Hải Dương", Country: "Việt Nam", Description: "Tỉnh đồng bằng Bắc Bộ" },
  { CityCode: "HBI", CityName: "Hòa Bình", Country: "Việt Nam", Description: "Tỉnh miền núi phía Bắc" },
  { CityCode: "HY", CityName: "Hưng Yên", Country: "Việt Nam", Description: "Tỉnh đồng bằng Bắc Bộ" },
  { CityCode: "KH", CityName: "Khánh Hòa", Country: "Việt Nam", Description: "Tỉnh duyên hải Nam Trung Bộ, nổi tiếng với Nha Trang" },
  { CityCode: "KG", CityName: "Kiên Giang", Country: "Việt Nam", Description: "Tỉnh Đồng bằng sông Cửu Long, có đảo Phú Quốc" },
  { CityCode: "LC", CityName: "Lào Cai", Country: "Việt Nam", Description: "Tỉnh miền núi Tây Bắc, có Sa Pa" },
  { CityCode: "LD", CityName: "Lâm Đồng", Country: "Việt Nam", Description: "Tỉnh Tây Nguyên, có Đà Lạt" },
  { CityCode: "LS", CityName: "Lạng Sơn", Country: "Việt Nam", Description: "Tỉnh miền núi phía Bắc, biên giới với Trung Quốc" },
  { CityCode: "LB", CityName: "Long An", Country: "Việt Nam", Description: "Tỉnh Đồng bằng sông Cửu Long" },
  { CityCode: "ND", CityName: "Nam Định", Country: "Việt Nam", Description: "Tỉnh đồng bằng Bắc Bộ" },
  { CityCode: "NA", CityName: "Nghệ An", Country: "Việt Nam", Description: "Tỉnh Bắc Trung Bộ, quê hương Bác Hồ" },
  { CityCode: "NB", CityName: "Ninh Bình", Country: "Việt Nam", Description: "Tỉnh đồng bằng Bắc Bộ, có Tràng An, Tam Cốc" },
  { CityCode: "NT", CityName: "Ninh Thuận", Country: "Việt Nam", Description: "Tỉnh duyên hải Nam Trung Bộ" },
  { CityCode: "PT", CityName: "Phú Thọ", Country: "Việt Nam", Description: "Tỉnh trung du miền núi phía Bắc, có Đền Hùng" },
  { CityCode: "PY", CityName: "Phú Yên", Country: "Việt Nam", Description: "Tỉnh duyên hải Nam Trung Bộ" },
  { CityCode: "QB", CityName: "Quảng Bình", Country: "Việt Nam", Description: "Tỉnh Bắc Trung Bộ, có động Phong Nha" },
  { CityCode: "QNA", CityName: "Quảng Nam", Country: "Việt Nam", Description: "Tỉnh Nam Trung Bộ, có Hội An, Mỹ Sơn" },
  { CityCode: "QNG", CityName: "Quảng Ngãi", Country: "Việt Nam", Description: "Tỉnh Nam Trung Bộ" },
  { CityCode: "QNI", CityName: "Quảng Ninh", Country: "Việt Nam", Description: "Tỉnh Đông Bắc, có Hạ Long, Móng Cái" },
  { CityCode: "QT", CityName: "Quảng Trị", Country: "Việt Nam", Description: "Tỉnh Bắc Trung Bộ" },
  { CityCode: "ST", CityName: "Sóc Trăng", Country: "Việt Nam", Description: "Tỉnh Đồng bằng sông Cửu Long" },
  { CityCode: "SL", CityName: "Sơn La", Country: "Việt Nam", Description: "Tỉnh miền núi Tây Bắc" },
  { CityCode: "TNI", CityName: "Tây Ninh", Country: "Việt Nam", Description: "Tỉnh miền Đông Nam Bộ, có núi Bà Đen" },
  { CityCode: "TB", CityName: "Thái Bình", Country: "Việt Nam", Description: "Tỉnh đồng bằng Bắc Bộ" },
  { CityCode: "TNG", CityName: "Thái Nguyên", Country: "Việt Nam", Description: "Tỉnh trung du miền núi phía Bắc" },
  { CityCode: "TH", CityName: "Thanh Hóa", Country: "Việt Nam", Description: "Tỉnh Bắc Trung Bộ" },
  { CityCode: "HUE", CityName: "Thừa Thiên Huế", Country: "Việt Nam", Description: "Tỉnh Bắc Trung Bộ, cố đô Huế" },
  { CityCode: "TG", CityName: "Tiền Giang", Country: "Việt Nam", Description: "Tỉnh Đồng bằng sông Cửu Long" },
  { CityCode: "TV", CityName: "Trà Vinh", Country: "Việt Nam", Description: "Tỉnh Đồng bằng sông Cửu Long" },
  { CityCode: "TQ", CityName: "Tuyên Quang", Country: "Việt Nam", Description: "Tỉnh miền núi phía Bắc" },
  { CityCode: "VL", CityName: "Vĩnh Long", Country: "Việt Nam", Description: "Tỉnh Đồng bằng sông Cửu Long" },
  { CityCode: "VP", CityName: "Vĩnh Phúc", Country: "Việt Nam", Description: "Tỉnh trung du miền núi phía Bắc" },
  { CityCode: "YB", CityName: "Yên Bái", Country: "Việt Nam", Description: "Tỉnh miền núi Tây Bắc" },
].map((city, index) => ({
  ...city,
  CityID: index + 1,
  Status: 1,
  CreatedAt: new Date().toISOString(),
  UpdatedAt: new Date().toISOString(),
}));


